### ISSUE TITLE
NAVAR.py incorrect view

### ISSUE THREAD

**Issue by m4urin** [bartbussmann/NAVAR#2]
Hi! I'm currently working with NAVAR for my thesis, but with a slightly different training setup.

Using the training implementation in this repo, the input tensor for `forward(x)`  in `NAVAR.py:37` is of size `(batch_size, num_nodes, kernel_size)` , then the first hidden layer applies a Conv1D that results in `(batch_size, num_nodes * hidden_nodes, 1)`, then a rehape is applied resulting in a view with `(-1, num_nodes, num_hidden)`. This view is correct as the last dimension is of size 1.

However, I am using it in a setting where the input is `(batch_size, num_nodes, time_steps)`, which results in `(batch_size, num_nodes * hidden_nodes, timesteps-kernel_size+1)`. In this case, the reshape/view is incorrect and mixes the values between isolated models. However,  it took me a while to notice this problem in my code, as it does not give any errors.

So, I wanted to suggest to add a `transpose(-1, -2).reshape(..)` to `NAVAR.py:38`, the reshape is necessary yo keep the tensor contiguous.
From:
`hidden = self.first_hidden_layer(x).clamp(min=0).view([-1, self.num_nodes, self.num_hidden])`
To:
`hidden = self.first_hidden_layer(x).clamp(min=0).transpose(-1, -2).reshape([-1, self.num_nodes, self.num_hidden])`

This will not change the performance/efficiency/result of the training setup using this repo, but it might save time in the future for someone that copies the implementation of the NAVAR model.

**Comment by bartbussmann** [comment]
Hi @m4urin,

It seems you've discovered a potential issue when using the NAVAR model with input tensors of size (batch_size, num_nodes, time_steps) instead of (batch_size, num_nodes, kernel_size). You're correct that the current implementation of the forward function in NAVAR.py may mix values between isolated models when the input tensor has a different size along the time dimension.

Your suggestion to modify the line NAVAR.py:38 to transpose the last two dimensions and reshape the tensor is a good one, as it combines the time dimension with the hidden dimension instead of the batch dimension and avoids mixing values between isolated models. 

As you mentioned, this change will not impact the performance, efficiency, or results of the original training setup. However, it can help prevent issues for users who adapt the NAVAR model implementation to different input tensor sizes in their own projects.

Thank you for pointing out this issue and suggesting a solution! Good luck with your thesis! Make sure to send me a copy when you are done ([username]@gmail.com), I'm always excited to see people using the model.
